# Generated by Django 6.0.3 on 2026-03-25 18:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2026, 3, 25, 18, 45, 52, 890708, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
